{
  "require": {
    "magento-hackathon/magento-composer-installer": "dev-master",
    "aperturelab/magento-mailjet": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/magento-hackathon/magento-composer-installer"
    },
    {
      "type": "vcs",
      "url": "https://github.com/ApertureLab/Magento-Mailjet.git"
    }
  ],
  "extra":{
    "magento-root-dir": "your-magento-root/"
  }
}