{
  "require": {
    "magento-hackathon/magento-composer-installer": "dev-master",
    "aperturelab/magento-mailjet": "dev-master"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "http://packages.firegento.com"
    },
    {
      "type": "vcs",
      "url": "https://github.com/ApertureLab/Magento-Mailjet.git"
    }
  ],
  "extra":{
    "magento-root-dir": "magento-1.9/",
    "magento-deploystrategy": "copy"
  }
}
